# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: authService.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'authService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61uthService.proto\",\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\r\n\x05\x63lave\x18\x02 \x01(\t\"?\n\rLoginResponse\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x1e\n\rLogoutRequest\x12\r\n\x05token\x18\x01 \x01(\t\"1\n\x0eLogoutResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2`\n\x0b\x41uthService\x12&\n\x05login\x12\r.LoginRequest\x1a\x0e.LoginResponse\x12)\n\x06logout\x12\x0e.LogoutRequest\x1a\x0f.LogoutResponseB&\n\x12RpcDonaciones.grpcB\x10\x41uthServiceProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'authService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\022RpcDonaciones.grpcB\020AuthServiceProto'
  _globals['_LOGINREQUEST']._serialized_start=21
  _globals['_LOGINREQUEST']._serialized_end=65
  _globals['_LOGINRESPONSE']._serialized_start=67
  _globals['_LOGINRESPONSE']._serialized_end=130
  _globals['_LOGOUTREQUEST']._serialized_start=132
  _globals['_LOGOUTREQUEST']._serialized_end=162
  _globals['_LOGOUTRESPONSE']._serialized_start=164
  _globals['_LOGOUTRESPONSE']._serialized_end=213
  _globals['_AUTHSERVICE']._serialized_start=215
  _globals['_AUTHSERVICE']._serialized_end=311
# @@protoc_insertion_point(module_scope)
