# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: usuarioService.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'usuarioService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14usuarioService.proto\"\xa8\x01\n\x0eUsuarioRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x15\n\rnombreUsuario\x18\x02 \x01(\t\x12\x0e\n\x06nombre\x18\x03 \x01(\t\x12\x10\n\x08\x61pellido\x18\x04 \x01(\t\x12\x10\n\x08telefono\x18\x05 \x01(\t\x12\r\n\x05\x65mail\x18\x06 \x01(\t\x12\x11\n\x03rol\x18\x07 \x01(\x0e\x32\x04.Rol\x12\x0e\n\x06\x61\x63tivo\x18\x08 \x01(\x08\x12\r\n\x05\x63lave\x18\t \x01(\t\"\x1e\n\x10UsuarioIdRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"\xbb\x01\n\x0fUsuarioResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x15\n\rnombreUsuario\x18\x02 \x01(\t\x12\x0e\n\x06nombre\x18\x03 \x01(\t\x12\x10\n\x08\x61pellido\x18\x04 \x01(\t\x12\x10\n\x08telefono\x18\x05 \x01(\t\x12\r\n\x05\x65mail\x18\x06 \x01(\t\x12\x11\n\x03rol\x18\x07 \x01(\x0e\x32\x04.Rol\x12\x0e\n\x06\x61\x63tivo\x18\x08 \x01(\x08\x12\x0e\n\x06status\x18\t \x01(\t\x12\x0f\n\x07message\x18\n \x01(\t\";\n\x17\x45liminarUsuarioResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x17\n\x15ListarUsuariosRequest\"<\n\x16ListarUsuariosResponse\x12\"\n\x08usuarios\x18\x01 \x03(\x0b\x32\x10.UsuarioResponse*A\n\x03Rol\x12\x0e\n\nPRESIDENTE\x10\x00\x12\t\n\x05VOCAL\x10\x01\x12\x0f\n\x0b\x43OORDINADOR\x10\x02\x12\x0e\n\nVOLUNTARIO\x10\x03\x32\xbb\x02\n\x0eUsuarioService\x12\x35\n\x10registrarUsuario\x12\x0f.UsuarioRequest\x1a\x10.UsuarioResponse\x12\x38\n\x11traerUsuarioPorId\x12\x11.UsuarioIdRequest\x1a\x10.UsuarioResponse\x12\x35\n\x10modificarUsuario\x12\x0f.UsuarioRequest\x1a\x10.UsuarioResponse\x12>\n\x0f\x65liminarUsuario\x12\x11.UsuarioIdRequest\x1a\x18.EliminarUsuarioResponse\x12\x41\n\x0elistarUsuarios\x12\x16.ListarUsuariosRequest\x1a\x17.ListarUsuariosResponseB)\n\x12RpcDonaciones.grpcB\x13UsuarioServiceProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'usuarioService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\022RpcDonaciones.grpcB\023UsuarioServiceProto'
  _globals['_ROL']._serialized_start=565
  _globals['_ROL']._serialized_end=630
  _globals['_USUARIOREQUEST']._serialized_start=25
  _globals['_USUARIOREQUEST']._serialized_end=193
  _globals['_USUARIOIDREQUEST']._serialized_start=195
  _globals['_USUARIOIDREQUEST']._serialized_end=225
  _globals['_USUARIORESPONSE']._serialized_start=228
  _globals['_USUARIORESPONSE']._serialized_end=415
  _globals['_ELIMINARUSUARIORESPONSE']._serialized_start=417
  _globals['_ELIMINARUSUARIORESPONSE']._serialized_end=476
  _globals['_LISTARUSUARIOSREQUEST']._serialized_start=478
  _globals['_LISTARUSUARIOSREQUEST']._serialized_end=501
  _globals['_LISTARUSUARIOSRESPONSE']._serialized_start=503
  _globals['_LISTARUSUARIOSRESPONSE']._serialized_end=563
  _globals['_USUARIOSERVICE']._serialized_start=633
  _globals['_USUARIOSERVICE']._serialized_end=948
# @@protoc_insertion_point(module_scope)
