# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import donacionService_pb2 as donacionService__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in donacionService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DonacionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.registrarDonacion = channel.unary_unary(
                '/DonacionService/registrarDonacion',
                request_serializer=donacionService__pb2.RegistrarDonacionRequest.SerializeToString,
                response_deserializer=donacionService__pb2.DonacionResponse.FromString,
                _registered_method=True)
        self.modificarDonacion = channel.unary_unary(
                '/DonacionService/modificarDonacion',
                request_serializer=donacionService__pb2.ModificarDonacionRequest.SerializeToString,
                response_deserializer=donacionService__pb2.DonacionResponse.FromString,
                _registered_method=True)
        self.eliminarDonacion = channel.unary_unary(
                '/DonacionService/eliminarDonacion',
                request_serializer=donacionService__pb2.EliminarDonacionRequest.SerializeToString,
                response_deserializer=donacionService__pb2.EliminarDonacionResponse.FromString,
                _registered_method=True)
        self.listarDonaciones = channel.unary_unary(
                '/DonacionService/listarDonaciones',
                request_serializer=donacionService__pb2.ListarDonacionesRequest.SerializeToString,
                response_deserializer=donacionService__pb2.ListarDonacionesResponse.FromString,
                _registered_method=True)
        self.traerDonacionPorId = channel.unary_unary(
                '/DonacionService/traerDonacionPorId',
                request_serializer=donacionService__pb2.DonacionIdRequest.SerializeToString,
                response_deserializer=donacionService__pb2.DonacionResponse.FromString,
                _registered_method=True)


class DonacionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def registrarDonacion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def modificarDonacion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def eliminarDonacion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listarDonaciones(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def traerDonacionPorId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DonacionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'registrarDonacion': grpc.unary_unary_rpc_method_handler(
                    servicer.registrarDonacion,
                    request_deserializer=donacionService__pb2.RegistrarDonacionRequest.FromString,
                    response_serializer=donacionService__pb2.DonacionResponse.SerializeToString,
            ),
            'modificarDonacion': grpc.unary_unary_rpc_method_handler(
                    servicer.modificarDonacion,
                    request_deserializer=donacionService__pb2.ModificarDonacionRequest.FromString,
                    response_serializer=donacionService__pb2.DonacionResponse.SerializeToString,
            ),
            'eliminarDonacion': grpc.unary_unary_rpc_method_handler(
                    servicer.eliminarDonacion,
                    request_deserializer=donacionService__pb2.EliminarDonacionRequest.FromString,
                    response_serializer=donacionService__pb2.EliminarDonacionResponse.SerializeToString,
            ),
            'listarDonaciones': grpc.unary_unary_rpc_method_handler(
                    servicer.listarDonaciones,
                    request_deserializer=donacionService__pb2.ListarDonacionesRequest.FromString,
                    response_serializer=donacionService__pb2.ListarDonacionesResponse.SerializeToString,
            ),
            'traerDonacionPorId': grpc.unary_unary_rpc_method_handler(
                    servicer.traerDonacionPorId,
                    request_deserializer=donacionService__pb2.DonacionIdRequest.FromString,
                    response_serializer=donacionService__pb2.DonacionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DonacionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('DonacionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DonacionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def registrarDonacion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DonacionService/registrarDonacion',
            donacionService__pb2.RegistrarDonacionRequest.SerializeToString,
            donacionService__pb2.DonacionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def modificarDonacion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DonacionService/modificarDonacion',
            donacionService__pb2.ModificarDonacionRequest.SerializeToString,
            donacionService__pb2.DonacionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def eliminarDonacion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DonacionService/eliminarDonacion',
            donacionService__pb2.EliminarDonacionRequest.SerializeToString,
            donacionService__pb2.EliminarDonacionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def listarDonaciones(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DonacionService/listarDonaciones',
            donacionService__pb2.ListarDonacionesRequest.SerializeToString,
            donacionService__pb2.ListarDonacionesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def traerDonacionPorId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DonacionService/traerDonacionPorId',
            donacionService__pb2.DonacionIdRequest.SerializeToString,
            donacionService__pb2.DonacionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
