# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import client.proto.eventoSolidarioService_pb2 as eventoSolidarioService__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in eventoSolidarioService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EventosServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateEvento = channel.unary_unary(
                '/EventosService/CreateEvento',
                request_serializer=eventoSolidarioService__pb2.CreateEventoRequest.SerializeToString,
                response_deserializer=eventoSolidarioService__pb2.CreateEventoResponse.FromString,
                _registered_method=True)
        self.GetEvento = channel.unary_unary(
                '/EventosService/GetEvento',
                request_serializer=eventoSolidarioService__pb2.GetEventoRequest.SerializeToString,
                response_deserializer=eventoSolidarioService__pb2.GetEventoResponse.FromString,
                _registered_method=True)
        self.UpdateEvento = channel.unary_unary(
                '/EventosService/UpdateEvento',
                request_serializer=eventoSolidarioService__pb2.UpdateEventoRequest.SerializeToString,
                response_deserializer=eventoSolidarioService__pb2.UpdateEventoResponse.FromString,
                _registered_method=True)
        self.DeleteEvento = channel.unary_unary(
                '/EventosService/DeleteEvento',
                request_serializer=eventoSolidarioService__pb2.DeleteEventoRequest.SerializeToString,
                response_deserializer=eventoSolidarioService__pb2.DeleteEventoResponse.FromString,
                _registered_method=True)
        self.ListEventos = channel.unary_unary(
                '/EventosService/ListEventos',
                request_serializer=eventoSolidarioService__pb2.ListEventosRequest.SerializeToString,
                response_deserializer=eventoSolidarioService__pb2.ListEventosResponse.FromString,
                _registered_method=True)


class EventosServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateEvento(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEvento(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateEvento(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteEvento(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEventos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventosServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateEvento': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEvento,
                    request_deserializer=eventoSolidarioService__pb2.CreateEventoRequest.FromString,
                    response_serializer=eventoSolidarioService__pb2.CreateEventoResponse.SerializeToString,
            ),
            'GetEvento': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEvento,
                    request_deserializer=eventoSolidarioService__pb2.GetEventoRequest.FromString,
                    response_serializer=eventoSolidarioService__pb2.GetEventoResponse.SerializeToString,
            ),
            'UpdateEvento': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateEvento,
                    request_deserializer=eventoSolidarioService__pb2.UpdateEventoRequest.FromString,
                    response_serializer=eventoSolidarioService__pb2.UpdateEventoResponse.SerializeToString,
            ),
            'DeleteEvento': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEvento,
                    request_deserializer=eventoSolidarioService__pb2.DeleteEventoRequest.FromString,
                    response_serializer=eventoSolidarioService__pb2.DeleteEventoResponse.SerializeToString,
            ),
            'ListEventos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEventos,
                    request_deserializer=eventoSolidarioService__pb2.ListEventosRequest.FromString,
                    response_serializer=eventoSolidarioService__pb2.ListEventosResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'EventosService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('EventosService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EventosService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateEvento(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EventosService/CreateEvento',
            eventoSolidarioService__pb2.CreateEventoRequest.SerializeToString,
            eventoSolidarioService__pb2.CreateEventoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEvento(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EventosService/GetEvento',
            eventoSolidarioService__pb2.GetEventoRequest.SerializeToString,
            eventoSolidarioService__pb2.GetEventoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateEvento(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EventosService/UpdateEvento',
            eventoSolidarioService__pb2.UpdateEventoRequest.SerializeToString,
            eventoSolidarioService__pb2.UpdateEventoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteEvento(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EventosService/DeleteEvento',
            eventoSolidarioService__pb2.DeleteEventoRequest.SerializeToString,
            eventoSolidarioService__pb2.DeleteEventoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEventos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EventosService/ListEventos',
            eventoSolidarioService__pb2.ListEventosRequest.SerializeToString,
            eventoSolidarioService__pb2.ListEventosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
