# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import usuarioService_pb2 as usuarioService__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in usuarioService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UsuarioServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.registrarUsuario = channel.unary_unary(
                '/usuario.UsuarioService/registrarUsuario',
                request_serializer=usuarioService__pb2.UsuarioRequest.SerializeToString,
                response_deserializer=usuarioService__pb2.UsuarioResponse.FromString,
                _registered_method=True)
        self.traerUsuarioPorId = channel.unary_unary(
                '/usuario.UsuarioService/traerUsuarioPorId',
                request_serializer=usuarioService__pb2.UsuarioIdRequest.SerializeToString,
                response_deserializer=usuarioService__pb2.UsuarioSinClave.FromString,
                _registered_method=True)
        self.modificarUsuario = channel.unary_unary(
                '/usuario.UsuarioService/modificarUsuario',
                request_serializer=usuarioService__pb2.UsuarioRequest.SerializeToString,
                response_deserializer=usuarioService__pb2.UsuarioResponse.FromString,
                _registered_method=True)
        self.eliminarUsuario = channel.unary_unary(
                '/usuario.UsuarioService/eliminarUsuario',
                request_serializer=usuarioService__pb2.UsuarioIdRequest.SerializeToString,
                response_deserializer=usuarioService__pb2.EliminarUsuarioResponse.FromString,
                _registered_method=True)
        self.listarUsuarios = channel.unary_unary(
                '/usuario.UsuarioService/listarUsuarios',
                request_serializer=usuarioService__pb2.ListarUsuariosRequest.SerializeToString,
                response_deserializer=usuarioService__pb2.ListarUsuariosResponse.FromString,
                _registered_method=True)
        self.traerUsuarioPorEmail = channel.unary_unary(
                '/usuario.UsuarioService/traerUsuarioPorEmail',
                request_serializer=usuarioService__pb2.UsuarioEmailRequest.SerializeToString,
                response_deserializer=usuarioService__pb2.UsuarioSinClave.FromString,
                _registered_method=True)


class UsuarioServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def registrarUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def traerUsuarioPorId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def modificarUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def eliminarUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listarUsuarios(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def traerUsuarioPorEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UsuarioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'registrarUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.registrarUsuario,
                    request_deserializer=usuarioService__pb2.UsuarioRequest.FromString,
                    response_serializer=usuarioService__pb2.UsuarioResponse.SerializeToString,
            ),
            'traerUsuarioPorId': grpc.unary_unary_rpc_method_handler(
                    servicer.traerUsuarioPorId,
                    request_deserializer=usuarioService__pb2.UsuarioIdRequest.FromString,
                    response_serializer=usuarioService__pb2.UsuarioSinClave.SerializeToString,
            ),
            'modificarUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.modificarUsuario,
                    request_deserializer=usuarioService__pb2.UsuarioRequest.FromString,
                    response_serializer=usuarioService__pb2.UsuarioResponse.SerializeToString,
            ),
            'eliminarUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.eliminarUsuario,
                    request_deserializer=usuarioService__pb2.UsuarioIdRequest.FromString,
                    response_serializer=usuarioService__pb2.EliminarUsuarioResponse.SerializeToString,
            ),
            'listarUsuarios': grpc.unary_unary_rpc_method_handler(
                    servicer.listarUsuarios,
                    request_deserializer=usuarioService__pb2.ListarUsuariosRequest.FromString,
                    response_serializer=usuarioService__pb2.ListarUsuariosResponse.SerializeToString,
            ),
            'traerUsuarioPorEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.traerUsuarioPorEmail,
                    request_deserializer=usuarioService__pb2.UsuarioEmailRequest.FromString,
                    response_serializer=usuarioService__pb2.UsuarioSinClave.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'usuario.UsuarioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('usuario.UsuarioService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UsuarioService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def registrarUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usuario.UsuarioService/registrarUsuario',
            usuarioService__pb2.UsuarioRequest.SerializeToString,
            usuarioService__pb2.UsuarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def traerUsuarioPorId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usuario.UsuarioService/traerUsuarioPorId',
            usuarioService__pb2.UsuarioIdRequest.SerializeToString,
            usuarioService__pb2.UsuarioSinClave.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def modificarUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usuario.UsuarioService/modificarUsuario',
            usuarioService__pb2.UsuarioRequest.SerializeToString,
            usuarioService__pb2.UsuarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def eliminarUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usuario.UsuarioService/eliminarUsuario',
            usuarioService__pb2.UsuarioIdRequest.SerializeToString,
            usuarioService__pb2.EliminarUsuarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def listarUsuarios(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usuario.UsuarioService/listarUsuarios',
            usuarioService__pb2.ListarUsuariosRequest.SerializeToString,
            usuarioService__pb2.ListarUsuariosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def traerUsuarioPorEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usuario.UsuarioService/traerUsuarioPorEmail',
            usuarioService__pb2.UsuarioEmailRequest.SerializeToString,
            usuarioService__pb2.UsuarioSinClave.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
